import { byteLength, canonicalJson, exactTime, retentionDigest } from "./canonical.js";
import { DELIVERY_ATTEMPT_RETENTION_DAYS, PROGRESS_RETENTION_DAYS, type RetentionCandidate, type RetentionException, type RetentionPlan, type RetentionReader } from "./types.js";
const DAY=86_400_000;
type O={id:string;workId:string;attemptId:string|null;authorityReference:string;holderInstanceId:string;fencingToken:number;observationKind:string;outcomeCode:string;evidenceDigest:string;createdAt:string};
type D={deliveryId:string;ordinal:number;claimEpoch:number;claimKind:string;endpointIdempotencyKey:string;claimant:string;startedAt:string;settledAt:string;disposition:string;errorCode:string|null;finalDisposition:string;terminalAt:string;destinationReference:string};
const bytes=(rows:readonly unknown[]):number=>rows.reduce<number>((n,r)=>n+byteLength(r),0);
function endpointClass(reference:string){const found=/^([a-z][a-z0-9_-]*):/.exec(reference)?.[1];if(!found)throw new Error("delivery destination lacks a privacy-safe endpoint class");return found;}
export function classifyRetention(reader:RetentionReader,options:{asOf:string;exceptions?:readonly RetentionException[]}):RetentionPlan{
 const now=exactTime(options.asOf,"retention asOf"),progressBefore=new Date(now-PROGRESS_RETENTION_DAYS*DAY).toISOString(),deliveryAttemptsBefore=new Date(now-DELIVERY_ATTEMPT_RETENTION_DAYS*DAY).toISOString();
 const exceptionMap=new Map<string,RetentionException>();for(const x of options.exceptions??[]){if((x.class!=="legal"&&x.class!=="security")||!/^[a-z][a-z0-9_-]*:[A-Za-z0-9._:-]+$/.test(x.reference))throw new Error("retention exception is not contract-permitted");if(exceptionMap.has(x.candidateKey))throw new Error("duplicate retention exception");exceptionMap.set(x.candidateKey,x);}
 const observations=reader.readAll<O>(`SELECT id,work_id AS workId,attempt_id AS attemptId,authority_reference AS authorityReference,holder_instance_id AS holderInstanceId,fencing_token AS fencingToken,observation_kind AS observationKind,outcome_code AS outcomeCode,evidence_digest AS evidenceDigest,created_at AS createdAt FROM work_observations WHERE observation_kind='running' AND created_at < ? ORDER BY work_id,created_at,id`,progressBefore);
 const candidates:RetentionCandidate[]=[];const og=new Map<string,O[]>();for(const r of observations){const k=`progress:${r.workId}`;og.set(k,[...(og.get(k)??[]),r]);}for(const [key,rows] of og){const sourceDigest=retentionDigest(rows),summary={kind:"noisy_progress",workId:rows[0]!.workId,sourceCount:rows.length,firstAt:rows[0]!.createdAt,lastAt:rows.at(-1)!.createdAt,outcomeCodes:[...new Set(rows.map(r=>r.outcomeCode))].sort(),sourceDigest};candidates.push({kind:"noisy_progress",key,sourceCount:rows.length,sourceBytes:bytes(rows),firstAt:summary.firstAt,lastAt:summary.lastAt,sourceDigest,sourceIds:rows.map(r=>r.id),summary});}
 const attempts=reader.readAll<D>(`SELECT a.delivery_id AS deliveryId,a.ordinal,a.claim_epoch AS claimEpoch,a.claim_kind AS claimKind,a.endpoint_idempotency_key AS endpointIdempotencyKey,a.claimant,a.started_at AS startedAt,a.settled_at AS settledAt,a.disposition,a.error_code AS errorCode,d.final_disposition AS finalDisposition,d.terminal_at AS terminalAt,o.destination_reference AS destinationReference FROM delivery_attempts a JOIN deliveries d ON d.id=a.delivery_id JOIN outbox o ON o.id=d.outbox_id WHERE a.settled_at < ? AND d.state IN ('delivered','permanent_failure','cancelled') AND a.disposition IS NOT NULL ORDER BY a.delivery_id,a.ordinal`,deliveryAttemptsBefore);
 const dg=new Map<string,D[]>();for(const r of attempts)dg.set(r.deliveryId,[...(dg.get(r.deliveryId)??[]),r]);for(const [deliveryId,rows] of dg){const sourceDigest=retentionDigest(rows),summary={kind:"delivery_attempt_detail",deliveryId,sourceCount:rows.length,firstAt:rows[0]!.startedAt,lastAt:rows.at(-1)!.settledAt,endpointClass:endpointClass(rows[0]!.destinationReference),finalDisposition:rows[0]!.finalDisposition,terminalAt:rows[0]!.terminalAt,errorClasses:[...new Set(rows.map(r=>r.errorCode).filter((x):x is string=>x!==null))].sort(),provenanceDigest:retentionDigest(rows.map(r=>({ordinal:r.ordinal,claimEpoch:r.claimEpoch,claimKind:r.claimKind,endpointIdempotencyKey:r.endpointIdempotencyKey,claimant:r.claimant}))),sourceDigest};candidates.push({kind:"delivery_attempt_detail",key:`delivery:${deliveryId}`,sourceCount:rows.length,sourceBytes:bytes(rows),firstAt:summary.firstAt,lastAt:summary.lastAt,sourceDigest,sourceIds:rows.map(r=>String(r.ordinal)),summary});}
 candidates.sort((a,b)=>a.key.localeCompare(b.key));for(const key of exceptionMap.keys())if(!candidates.some(c=>c.key===key))throw new Error(`retention exception does not match an eligible candidate: ${key}`);const eligible=candidates.filter(c=>!exceptionMap.has(c.key)),exceptions=[...exceptionMap.values()].sort((a,b)=>a.candidateKey.localeCompare(b.candidateKey));const core={version:1 as const,asOf:options.asOf,cutoffs:{progressBefore,deliveryAttemptsBefore},candidates:eligible,exceptions,totals:{candidates:eligible.length,sourceRows:eligible.reduce((n,c)=>n+c.sourceCount,0),sourceBytes:eligible.reduce((n,c)=>n+c.sourceBytes,0)}};return Object.freeze({...core,digest:retentionDigest(JSON.parse(canonicalJson(core)))});
}
