/** M30-owned proposal; deliberately not wired into the canonical migration chain. */
export const RETENTION_SCHEMA_DELTA_SQL = `
CREATE TABLE retention_progress_summaries (summary_digest TEXT PRIMARY KEY CHECK(length(summary_digest)=64),work_id TEXT NOT NULL REFERENCES works(id),source_ids_json TEXT NOT NULL CHECK(json_valid(source_ids_json) AND json_type(source_ids_json)='array'),source_count INTEGER NOT NULL CHECK(source_count>0),source_bytes INTEGER NOT NULL CHECK(source_bytes>0),first_at TEXT NOT NULL CHECK(length(first_at)=24),last_at TEXT NOT NULL CHECK(length(last_at)=24),source_digest TEXT NOT NULL CHECK(length(source_digest)=64),summary_json TEXT NOT NULL CHECK(json_valid(summary_json) AND json_type(summary_json)='object'),compacted_at TEXT NOT NULL CHECK(length(compacted_at)=24),UNIQUE(work_id,source_digest),CHECK(json_array_length(source_ids_json)=source_count)) STRICT;
CREATE TABLE retention_delivery_summaries (summary_digest TEXT PRIMARY KEY CHECK(length(summary_digest)=64),delivery_id TEXT NOT NULL UNIQUE REFERENCES deliveries(id),source_ordinals_json TEXT NOT NULL CHECK(json_valid(source_ordinals_json) AND json_type(source_ordinals_json)='array'),source_count INTEGER NOT NULL CHECK(source_count>0),source_bytes INTEGER NOT NULL CHECK(source_bytes>0),first_at TEXT NOT NULL CHECK(length(first_at)=24),last_at TEXT NOT NULL CHECK(length(last_at)=24),source_digest TEXT NOT NULL CHECK(length(source_digest)=64),summary_json TEXT NOT NULL CHECK(json_valid(summary_json) AND json_type(summary_json)='object'),compacted_at TEXT NOT NULL CHECK(length(compacted_at)=24),CHECK(json_array_length(source_ordinals_json)=source_count)) STRICT;
DROP TRIGGER work_observations_no_delete;
CREATE TRIGGER work_observations_no_delete BEFORE DELETE ON work_observations WHEN NOT EXISTS (SELECT 1 FROM retention_progress_summaries s,json_each(s.source_ids_json) j WHERE j.value=OLD.id) BEGIN SELECT RAISE(ABORT,'work observation is retained unless covered by M30 summary'); END;
DROP TRIGGER delivery_attempts_no_delete;
CREATE TRIGGER delivery_attempts_no_delete BEFORE DELETE ON delivery_attempts WHEN NOT EXISTS (SELECT 1 FROM retention_delivery_summaries s,json_each(s.source_ordinals_json) j WHERE s.delivery_id=OLD.delivery_id AND j.value=OLD.ordinal) BEGIN SELECT RAISE(ABORT,'delivery attempt is retained unless covered by M30 summary'); END;
CREATE TRIGGER retention_progress_summaries_no_update BEFORE UPDATE ON retention_progress_summaries BEGIN SELECT RAISE(ABORT,'retention summary is immutable'); END;
CREATE TRIGGER retention_progress_summaries_no_delete BEFORE DELETE ON retention_progress_summaries BEGIN SELECT RAISE(ABORT,'retention summary is retained'); END;
CREATE TRIGGER retention_delivery_summaries_no_update BEFORE UPDATE ON retention_delivery_summaries BEGIN SELECT RAISE(ABORT,'retention summary is immutable'); END;
CREATE TRIGGER retention_delivery_summaries_no_delete BEFORE DELETE ON retention_delivery_summaries BEGIN SELECT RAISE(ABORT,'retention summary is retained'); END;
`;
