import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, cpSync, readFileSync, writeFileSync, rmSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createRequire } from 'node:module';
import yaml from 'js-yaml';
import { createHome, homeCreationJournalPath } from '../../cli/lib/create-home.js';
import { loadCoordinationRuntimeConfig } from '../../dist/coordination/app/runtime-config.js';
const require = createRequire(import.meta.url);
const profile = { name: 'milo', displayName: 'Milo', ownerName: 'Alex', purpose: 'Help with family plans and creative projects.', provider: 'openai', model: 'gpt-5.5-pro', timezone: 'UTC', personalFacts: 'Prefers concise conversation.' };
function fixture(t) {
  const root = mkdtempSync(join(tmpdir(), 'h23-birth-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  mkdirSync(join(root, 'config'));
  cpSync(new URL('../../cli/templates/', import.meta.url), join(root, 'cli', 'templates'), { recursive: true });
  writeFileSync(join(root, 'config', 'home.yaml'), readFileSync(new URL('../../config/home.yaml.example', import.meta.url), 'utf8'));
  writeFileSync(join(root, 'config', 'secrets.yaml'), yaml.dump({ providers: { openai: { apiKey: 'fixture-provider-key' } } }));
  symlinkSync(resolve('node_modules'), join(root, 'node_modules'), 'dir');
  return root;
}
test('one operation prepares a distinct canonical home and Seed with matching launch configuration', async t => {
  const root = fixture(t);
  const result = await createHome(root, profile);
  assert.equal(result.status, 'prepared');
  assert.equal(result.agent.name, 'milo');
  const home = yaml.load(readFileSync(join(root, 'config/home.yaml'), 'utf8'));
  assert.equal(home.home.primaryAgent, 'milo');
  assert.deepEqual(home.coordination.residentSlugs, ['milo']);
  assert.match(readFileSync(join(root, 'instances/milo/workspace/PERSONAL.md'), 'utf8'), /Prefers concise conversation/);
  const generated = require(join(root, 'ecosystem.config.cjs'));
  const core = generated.apps.find(app => app.name === 'home23-coordination');
  const seed = generated.apps.find(app => app.name === 'home23-milo-seed');
  const harness = generated.apps.find(app => app.name === 'home23-milo-harness');
  assert.equal(core.autostart, true);
  assert.equal(harness.env.COSMO_CONFIG_PATH, join(root, 'instances/milo/engine.yaml'));
  const engine = yaml.load(readFileSync(harness.env.COSMO_CONFIG_PATH, 'utf8'));
  assert.deepEqual(engine.modelAssignments.default, { provider: 'openai', model: profile.model });
  assert.doesNotMatch(JSON.stringify(engine), /jtr|jerry/i);
  assert.equal(core.env.HOME23_COORDINATION_PRIMARY_RESIDENT, 'milo');
  assert.equal(seed.env.SEED_NAME, 'milo');
  assert.equal(seed.env.SEED_SELF_FORMATION, 'true');
  assert.equal(seed.env.SEED_LOBE_PROVIDER, 'openai');
  assert.equal(JSON.parse(seed.env.SEED_ANATOMY)[0].id, 'contact.owner');
  assert.equal(harness.env.HOME23_COORDINATION_RESIDENT_ENABLED, 'true');
  assert.equal(harness.env.HOME23_COORDINATION_RESIDENT_KEY, core.env.HOME23_COORDINATION_RESIDENT_MILO_KEY);
  assert.ok(generated.apps.some(app => app.name === 'home23-milo-shipper'));
  const runtime = loadCoordinationRuntimeConfig(core.env);
  assert.equal(runtime.home.primaryResident, 'milo');
  const serialized = readFileSync(homeCreationJournalPath(root), 'utf8');
  assert.ok(!serialized.includes('fixture-provider-key'));
  assert.ok(!serialized.includes(core.env.HOME23_COORDINATION_RESIDENT_MILO_KEY));
});
test('interrupted creation resumes stable identity without overwriting resident memory or rotating keys', async t => {
  const root = fixture(t);
  await assert.rejects(createHome(root, profile, { afterStep: step => { if (step === 'canonical-home') throw new Error('power interrupted'); } }), /power interrupted/);
  const journal = JSON.parse(readFileSync(homeCreationJournalPath(root), 'utf8'));
  const secrets = readFileSync(join(root, 'config/secrets.yaml'), 'utf8');
  const memory = join(root, 'instances/milo/workspace/MEMORY.md');
  writeFileSync(memory, 'An actual memory acquired before retry.');
  const result = await createHome(root, profile);
  assert.equal(result.home.id, journal.home.id);
  assert.equal(readFileSync(memory, 'utf8'), 'An actual memory acquired before retry.');
  assert.equal(readFileSync(join(root, 'config/secrets.yaml'), 'utf8'), secrets);
  const ecosystem = readFileSync(join(root, 'ecosystem.config.cjs'), 'utf8');
  const repeat = await createHome(root, profile);
  assert.equal(repeat.replayed, true);
  assert.equal(repeat.coordination.botId, result.coordination.botId);
  assert.equal(repeat.seed.seedId, result.seed.seedId);
  assert.equal(readFileSync(join(root, 'ecosystem.config.cjs'), 'utf8'), ecosystem);
  await assert.rejects(createHome(root, { ...profile, ownerName: 'Somebody else' }), /different creation request/);
});
test('fresh creation refuses existing homes and concurrent calls converge on one home', async t => {
  const occupied = fixture(t);
  mkdirSync(join(occupied, 'instances/already-here'), { recursive: true });
  await assert.rejects(createHome(occupied, profile), /only for a new installation/);
  const root = fixture(t);
  const results = await Promise.all([createHome(root, profile), createHome(root, profile)]);
  assert.equal(results[0].home.id, results[1].home.id);
  assert.equal(results[0].seed.seedId, results[1].seed.seedId);
  assert.equal(results.filter(result => result.replayed).length, 1);
});

test('invalid model pair or unsupported resident name is rejected before claiming a home', async t => {
  const root = fixture(t);
  await assert.rejects(createHome(root, { ...profile, model: 'made-up-model' }));
  await assert.rejects(createHome(root, { ...profile, name: '23home' }), /starting with a lowercase letter/);
  assert.throws(() => readFileSync(homeCreationJournalPath(root)), /ENOENT/);
});

test('browser setup resumes an interrupted home and exposes its actual engine defaults', async t => {
  const root = fixture(t);
  await assert.rejects(createHome(root, profile, { afterStep: () => { throw new Error('interrupted'); } }), /interrupted/);
  const express = require('express');
  const { createSettingsRouter } = require('../../engine/src/dashboard/home23-settings-api.js');
  const app = express(); app.use(express.json());
  app.use('/settings', createSettingsRouter(root, { recycleManagedProcess: () => false }).router);
  const server = await new Promise(resolve => { const server = app.listen(0, '127.0.0.1', () => resolve(server)); });
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}/settings`;
  const pending = await (await fetch(`${base}/home/creation`)).json();
  assert.equal(pending.status, 'preparing');
  assert.equal(pending.agentName, 'milo');
  assert.equal((await fetch(`${base}/agents/milo/start`, { method: 'POST' })).status, 409);
  const resumedResponse = await fetch(`${base}/home/creation/resume`, { method: 'POST' });
  const resumed = await resumedResponse.json();
  assert.equal(resumedResponse.status, 200, JSON.stringify(resumed));
  assert.equal(resumed.preparation.status, 'prepared');
  assert.equal((await (await fetch(`${base}/home/creation`)).json()).status, 'prepared');
  const defaults = await (await fetch(`${base}/model-assignments?agent=milo`)).json();
  assert.ok(JSON.stringify(defaults).includes(profile.model));
  assert.ok(!JSON.stringify(defaults.baseAssignments || {}).includes('minimax'));
  const feeder = await (await fetch(`${base}/feeder?agent=milo`)).json();
  assert.equal(feeder.inheritedFrom, join(root, 'instances/milo/engine.yaml'));
  assert.equal(feeder.feeder.compiler.model, profile.model);
});
