// ecosystem.config.cjs — PM2 process configuration
//
// This file is auto-generated by `node cli/home23.js start <agent>`.
// Do not edit manually. It will be overwritten on next start.
//
// To regenerate: node cli/home23.js start <agent-name>

module.exports = { apps: [] };
