import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const HOME23_ROOT = process.cwd();

test('live-problems panel exposes an operator readout, not only raw verifier rows', () => {
  const js = fs.readFileSync(path.join(HOME23_ROOT, 'engine/src/dashboard/home23-dashboard.js'), 'utf8');
  const css = fs.readFileSync(path.join(HOME23_ROOT, 'engine/src/dashboard/home23-dashboard.css'), 'utf8');
  const html = fs.readFileSync(path.join(HOME23_ROOT, 'engine/src/dashboard/home23-dashboard.html'), 'utf8');

  assert.match(html, /h23-problems-overlay-panel/);
  assert.match(js, /renderProblemsOperatorSummary/);
  assert.match(js, /Operator Status/);
  assert.match(js, /Needed From You/);
  assert.match(js, /problemRepairText/);
  assert.match(js, /renderProblemUserAction/);
  assert.match(js, /Action Needed/);
  assert.match(js, /Inspect Plan/);
  assert.match(js, /Mark Handled \+ Re-check/);
  assert.match(js, /recordProblemUserIntervention/);
  assert.match(js, /recordGoodLifeUserIntervention/);
  assert.match(js, /user-intervention/);
  assert.match(js, /Verifier remains the source of truth/);
  assert.match(js, /Re-check/);
  assert.match(js, /manual review needed; autonomous remediation has escalated this issue/);
  assert.match(js, /problem\.escalated === true/);
  assert.match(js, /nothing; this issue is resolved/);
  assert.match(js, /brief\.status === 'Paused'/);
  assert.match(js, /paused by budget/);
  assert.match(js, /brief\.status === 'Resting'/);
  assert.match(js, /resting autonomously/);
  assert.match(js, /goodLifePausedFleetText/);
  assert.match(js, /budget \$\{reset\}/);
  assert.match(js, /renderGoodLifeHostPressure/);
  assert.match(js, /renderGoodLifePm2Changes/);
  assert.match(js, /Runtime Changes/);
  assert.match(js, /renderGoodLifeWorkerReceiptDetail/);
  assert.match(js, /renderGoodLifeIssueWorkerReceipt/);
  assert.match(js, /Latest Worker Receipt/);
  assert.match(js, /renderGoodLifeIssueInterventionConsole/);
  assert.match(js, /Operator Intervention/);
  assert.match(js, /Recommended next step/);
  assert.match(js, /Projection Provenance/);
  assert.match(js, /provenance\.projection\?\.authority/);
  assert.match(js, /From The Inside arc/);
  assert.match(js, /provenance\.curriculumArc\.issuesRead/);
  assert.match(js, /provenance\.conflicts/);
  assert.match(js, /Ask \$\{escapeHtml\(workerName\)\} Worker/);
  assert.match(js, /openGoodLifeWorkers/);
  assert.match(js, /Run Engine Check/);
  assert.match(js, /h23-goodlife-primary-action/);
  assert.match(js, /Next Action/);
  assert.match(js, /Work Manifest/);
  assert.match(js, /manifest\.allowedTransition/);
  assert.match(js, /manifest\.sourceSurface/);
  assert.match(js, /Correction Tombstones/);
  assert.match(js, /correctionTombstones/);
  assert.match(js, /do_not_inherit_old_projection/);
  assert.match(js, /Restraint Receipts/);
  assert.match(js, /restraintReceipts/);
  assert.match(js, /Scheduler Sovereignty/);
  assert.match(js, /renderGoodLifeScheduler/);
  assert.match(js, /Doctrine Adoption/);
  assert.match(js, /doctrineAdoption\.reusable/);
  assert.match(js, /doctrineAdoption\.blocked/);
  assert.match(js, /renderGoodLifeRings/);
  assert.match(js, /Good Life three-ring status/);
  assert.match(js, /operatorRings/);
  assert.match(js, /formatGoodLifeWorkerResult/);
  assert.match(js, /Worker check complete: \$\{formatGoodLifeWorkerResult/);
  assert.match(js, /last change/);
  assert.match(js, /currently not online/);
  assert.match(js, /repair signal/);
  assert.match(js, /compactGoodLifeHostDetail/);
  assert.match(js, /Host Pressure/);
  assert.match(js, /CPU Load/);
  assert.match(js, /Top Process/);
  assert.match(js, /goodLifeHostPressureStatus/);
  assert.match(js, /drives rest/);
  assert.match(js, /informational/);
  assert.match(css, /\.h23-problems-operator/);
  assert.match(css, /\.h23-problem-operator-grid/);
  assert.match(css, /\.h23-problem-user-action/);
  assert.match(css, /\.h23-goodlife-fleet-row\.paused/);
  assert.match(css, /\.h23-goodlife-fleet-row\.resting/);
  assert.match(css, /\.h23-goodlife-evidence-row\.watch/);
  assert.match(css, /\.h23-goodlife-evidence-row\.info/);
  assert.match(css, /\.h23-goodlife-intervention-console/);
  assert.match(css, /\.h23-goodlife-intervention-grid/);
  assert.match(css, /\.h23-goodlife-primary-action/);
  assert.match(css, /\.h23-goodlife-primary-action \.h23-goodlife-mini-actions[\s\S]*flex:\s*0 0 auto/);
  assert.match(css, /\.h23-goodlife-rings/);
  assert.match(css, /\.h23-goodlife-ring\.needs-user/);
  assert.match(css, /\.h23-goodlife-overlay-body[\s\S]*grid-template-rows:\s*minmax\(180px,\s*0\.82fr\)\s*auto\s*minmax\(260px,\s*1\.18fr\)\s*auto/);
  assert.match(css, /\.h23-goodlife-overlay-top[\s\S]*overflow-y:\s*auto/);
  assert.match(css, /\.h23-goodlife-overlay-workspace[\s\S]*overflow:\s*hidden/);
  assert.match(css, /\.h23-goodlife-overlay-list,\s*\n\.h23-goodlife-overlay-detail[\s\S]*overflow-y:\s*auto/);
  assert.match(css, /\.h23-goodlife-overlay-action-status[\s\S]*pointer-events:\s*none/);
});

test('Good Life issue detail shows user-facing repair context before raw JSON', () => {
  const js = fs.readFileSync(path.join(HOME23_ROOT, 'engine/src/dashboard/home23-dashboard.js'), 'utf8');
  const css = fs.readFileSync(path.join(HOME23_ROOT, 'engine/src/dashboard/home23-dashboard.css'), 'utf8');

  assert.match(js, /h23-goodlife-issue-brief/);
  assert.match(js, /What is wrong/);
  assert.match(js, /What is happening/);
  assert.match(js, /Needed from jtr/);
  assert.match(js, /Stop condition/);
  assert.match(css, /\.h23-goodlife-issue-brief/);
});

test('Agency inspector exposes cron retirement proposals as a filtered proof-chain surface', () => {
  const js = fs.readFileSync(path.join(HOME23_ROOT, 'engine/src/dashboard/home23-dashboard.js'), 'utf8');
  const css = fs.readFileSync(path.join(HOME23_ROOT, 'engine/src/dashboard/home23-dashboard.css'), 'utf8');
  const html = fs.readFileSync(path.join(HOME23_ROOT, 'engine/src/dashboard/home23-dashboard.html'), 'utf8');
  const server = fs.readFileSync(path.join(HOME23_ROOT, 'engine/src/dashboard/server.js'), 'utf8');

  assert.match(html, /agency-retirement-proposals/);
  assert.match(html, /Cron Retirement Proposals/);
  const agencyStats = html.match(/<div class="h23-worker-stats" id="agency-stats">[\s\S]*?<\/div>\s*<\/div>/)?.[0] || '';
  assert.match(agencyStats, /Needs jtr/);
  assert.match(agencyStats, /Next Authority/);
  assert.doesNotMatch(agencyStats, />Inbox</);
  assert.doesNotMatch(agencyStats, />Receipts</);
  assert.match(html, /<details class="h23-agency-evidence-drawer" id="agency-scratch-drawer">/);
  assert.match(html, /<details class="h23-agency-evidence-drawer" id="agency-truth-drawer">/);
  assert.match(html, /<details class="h23-agency-evidence-drawer" id="agency-organs-drawer">/);
  assert.match(html, /<details class="h23-agency-evidence-drawer" id="agency-retirement-drawer" hidden>/);
  assert.match(html, /<details class="h23-agency-evidence-drawer" id="agency-receipts-drawer">/);
  assert.match(html, /<details class="h23-agency-evidence-drawer" id="agency-inbox-drawer">/);
  assert.match(html, /<details class="h23-agency-evidence-drawer" id="agency-consequences-drawer">/);
  assert.doesNotMatch(html, /<details class="h23-agency-evidence-drawer" id="agency-brief-drawer">/);
  assert.doesNotMatch(html, /<details class="h23-agency-evidence-drawer" id="agency-pursuits-drawer">/);
  assert.match(js, /\/home23\/api\/agency\/inspector\?filter=cron_retirement_proposals/);
  assert.match(js, /renderAgencyRetirementProposalRow/);
  assert.match(js, /agency-retirement-drawer/);
  assert.match(js, /retirementDrawer\.hidden = !proposals\.length/);
  assert.match(js, /agencyOperatorNeedCount\(state, brief\)/);
  assert.match(js, /residentAgencyModeLabel\(state\.mode\)/);
  assert.match(js, /residentActionAuthorityLabel\(state\.nextAction\)/);
  assert.doesNotMatch(js, /\$\{escapeHtml\(state\.mode \|\| 'unknown'\)\}/);
  assert.doesNotMatch(js, /<label>Inbox<\/label>/);
  assert.doesNotMatch(js, /<label>Recent Receipts<\/label>/);
  assert.doesNotMatch(js, /state\.attention\?\.queueDepth/);
  assert.match(js, /residentAgencyVisiblePursuits\(state, pursuits\)/);
  assert.match(js, /function residentAgencyVisiblePursuits\(state, pursuits = \[\]\)/);
  assert.match(js, /Array\.isArray\(state\.activePursuits\) \? state\.activePursuits : pursuits/);
  assert.match(js, /status !== 'discarded' && status !== 'closed'/);
  assert.doesNotMatch(js, /pursuits\.length \? pursuits\.map\(renderAgencyPursuitRow\)/);
  assert.match(js, /renderAgencyBriefQuestionBlock/);
  assert.match(js, /agencyMeaningfulBriefChanges/);
  assert.match(js, /summary !== 'pursuit_has_no_editor_block'/);
  assert.match(js, /kind !== 'explicit_no_change'/);
  assert.match(js, /Neighbor report from/);
  assert.match(js, /renderAgencyCandidateTitle/);
  assert.match(js, /Machine memory telemetry/);
  assert.match(js, /Machine CPU telemetry/);
  assert.match(js, /Work heartbeat/);
  assert.doesNotMatch(js, /<div>\$\{escapeHtml\(c\.title \|\| c\.summary \|\| c\.candidateId\)\}<\/div>/);
  assert.doesNotMatch(js, /<pre style="white-space:pre-wrap/);
  assert.doesNotMatch(js, /brief\.text/);
  assert.match(css, /\.h23-agency-brief-block/);
  assert.match(css, /\.h23-agency-brief-row/);
  assert.match(css, /\.h23-agency-evidence-drawer/);
  assert.match(css, /\.h23-agency-evidence-drawer > summary/);
  assert.match(js, /cron_run_log_excerpt/);
  assert.match(js, /semanticStatus/);
  assert.match(server, /\/home23\/api\/agency\/inspector/);
});

test('Home dashboard is resident agency command surface, not legacy tile theater', () => {
  const js = fs.readFileSync(path.join(HOME23_ROOT, 'engine/src/dashboard/home23-dashboard.js'), 'utf8');
  const css = fs.readFileSync(path.join(HOME23_ROOT, 'engine/src/dashboard/home23-dashboard.css'), 'utf8');
  const html = fs.readFileSync(path.join(HOME23_ROOT, 'engine/src/dashboard/home23-dashboard.html'), 'utf8');
  const server = fs.readFileSync(path.join(HOME23_ROOT, 'engine/src/dashboard/server.js'), 'utf8');

  assert.match(html, /id="resident-home"/);
  assert.match(html, /id="resident-next-action"/);
  assert.match(html, /id="resident-active-pursuits"/);
  assert.match(html, /id="resident-consequences"/);
  assert.match(html, /id="resident-consequence-panel"/);
  assert.match(html, /id="resident-operator-needed"/);
  const residentOperatorTag = html.match(/<section[^>]*id="resident-operator-needed"[^>]*>/)?.[0] || '';
  const residentConsequenceTag = html.match(/<section[^>]*id="resident-consequence-panel"[^>]*>/)?.[0] || '';
  assert.match(residentOperatorTag, /\bhidden\b/);
  assert.match(residentConsequenceTag, /\bhidden\b/);
  assert.doesNotMatch(html, /h23-resident-diagnostics/);
  assert.doesNotMatch(html, /id="resident-receipts"/);
  assert.doesNotMatch(html, /id="resident-inbox"/);
  assert.doesNotMatch(html, /Receipts and Inbox/);
  assert.doesNotMatch(html, /id="home-layout-grid"/);
  assert.doesNotMatch(html, /COSMO status indicator/);
  assert.doesNotMatch(html, /Engine State/);
  assert.doesNotMatch(html, /Active Goals/);
  assert.doesNotMatch(html, /sidebar-status-card/);
  assert.doesNotMatch(html, /Check for updates/);
  assert.doesNotMatch(html, /id="particles-js"/);
  assert.doesNotMatch(html, /particles\.js/);
  assert.doesNotMatch(html, /h23-sidebar-orb/);
  assert.doesNotMatch(html, /class="h23-sidebar-group"/);
  assert.doesNotMatch(html, /h23-overview-band/);
  assert.doesNotMatch(html, /h23-tab-scope-bar/);
  assert.doesNotMatch(html, />This Agent Surface</);
  assert.doesNotMatch(html, /id="panel-intelligence"/);
  assert.doesNotMatch(html, /id="panel-about"/);
  assert.doesNotMatch(html, /Dashboard Guide/);
  assert.doesNotMatch(html, /Live view of thoughts, vibe images, chat, brain log, dream log, feeder status/);
  assert.doesNotMatch(html, /dashboard-identity-chip/);
  assert.doesNotMatch(html, /PRIMARY AGENT/);
  const primaryNav = html.match(/<nav class="h23-tabs h23-tabs-primary">[\s\S]*?<\/nav>/)?.[0] || '';
  const organDrawer = html.match(/<details class="h23-organ-drawer" id="organs-drawer">[\s\S]*?<\/details>/)?.[0] || '';
  const residentCommandRow = html.match(/<div class="h23-resident-command-row">[\s\S]*?<\/div>/)?.[0] || '';
  assert.doesNotMatch(primaryNav, /data-tab="workers"/);
  assert.match(organDrawer, /data-tab="workers"/);
  assert.doesNotMatch(residentCommandRow, /href="\/home23\/chat"/);
  assert.doesNotMatch(residentCommandRow, /href="\/home23\/settings#agency"/);
  assert.doesNotMatch(residentCommandRow, />Chat</);
  assert.doesNotMatch(residentCommandRow, />Authority</);
  assert.doesNotMatch(residentCommandRow, /id="resident-refresh"/);
  assert.doesNotMatch(residentCommandRow, />Refresh</);
  assert.match(html, /h23-system-rail/);
  assert.match(html, /h23-system-runtime/);
  assert.match(html, /id="organs-drawer"/);
  assert.match(html, /class="h23-organ-drawer"/);
  assert.match(html, /Runtime/);
  assert.doesNotMatch(html, /time-cluster/);
  assert.doesNotMatch(html, /id="engine-status"/);
  assert.doesNotMatch(html, />ENGINE</);
  assert.match(html, />Rehearse</);
  assert.doesNotMatch(html, />Run Tick</);
  assert.doesNotMatch(html, /h23-system-metric/);

  assert.match(js, /loadResidentHomeSurface/);
  assert.match(js, /if \(!primaryAgent\) return/);
  assert.doesNotMatch(js, /if \(!chip \|\| !primaryAgent\) return/);
  assert.doesNotMatch(js, /PRIMARY AGENT/);
  assert.doesNotMatch(js, /SECONDARY AGENT/);
  assert.match(js, /renderResidentHomeSurface/);
  assert.match(js, /residentPostureText\(state\)/);
  assert.match(js, /function residentPostureText\(state/);
  assert.match(js, /return 'in agency bootcamp'/);
  assert.doesNotMatch(js, /\[state\.mode \|\| 'unknown', state\.bootcamp\?\.enabled \? 'bootcamp' : null\]\.filter\(Boolean\)\.join\(' \/ '\)/);
  assert.doesNotMatch(js, /setHtml\('resident-receipts'/);
  assert.doesNotMatch(js, /setHtml\('resident-inbox'/);
  assert.match(js, /residentBriefCountText/);
  assert.match(js, /return needed \?/);
  assert.doesNotMatch(js, /nothing needed from jtr/);
  assert.match(js, /renderResidentAttentionBudget/);
  assert.match(js, /toggleResidentOperatorPanel/);
  assert.doesNotMatch(js, />Nothing right now\.</);
  assert.doesNotMatch(js, />\$\{Number\(state\.attention\?\.deferredItems/);
  assert.doesNotMatch(js, />\$\{Number\(state\.attention\?\.openTasks/);
  assert.match(js, /runResidentTickFromDashboard/);
  assert.match(js, /syncResidentActionButton\(state\)/);
  assert.match(js, /residentActionButtonState\(state\)/);
  assert.match(js, /button\.textContent = isRehearsal \? 'Rehearsing' : 'Advancing'/);
  assert.match(js, /syncResidentActionButton\(residentHomeLatestState\)/);
  assert.doesNotMatch(js, /button\.textContent = 'Advance'/);
  assert.doesNotMatch(js, /button\.textContent = 'Run Tick'/);
  assert.match(js, /openCount <= 0/);
  assert.doesNotMatch(js, /all clear/);
  assert.doesNotMatch(js, /badge\.textContent = `✨ \$\{signals\.length\}`/);
  assert.match(js, /transitionResidentPursuitFromDashboard/);
  assert.match(js, /\/home23\/api\/agency\/tick/);
  assert.match(js, /\/home23\/api\/agency\/pursuits\/\$\{encodeURIComponent\(pursuitId\)\}\/transition/);
  assert.match(js, /currentTab === 'home'\) loadResidentHomeSurface/);
  assert.match(js, /setupOrganDrawer/);
  assert.match(js, /syncOrganDrawerForTab/);
  assert.doesNotMatch(js, /particlesJS/);
  assert.match(js, /humanizeResidentMachineText/);
  assert.match(js, /if \(value === 'domain\.good-life'\) return 'Good Life'/);
  assert.match(js, /renderGoodLifeResidentPursuitTitle/);
  assert.match(js, /renderResidentPursuitTitle/);
  assert.match(js, /renderResidentPursuitBody/);
  assert.match(js, /renderResidentPursuitEvidence/);
  assert.doesNotMatch(js, /\[compactResidentEvidenceId\(p\.id\), residentSourceLabel\(p\.source\)/);
  assert.match(js, /renderResidentNextActionTitle/);
  assert.match(js, /function renderResidentNextActionTitle\(pursuit, next\)[\s\S]*renderGoodLifeResidentPursuitTitle/);
  assert.match(js, /renderResidentNextActionMeta\(pursuit, next\)/);
  assert.match(js, /function renderResidentNextActionMeta\(pursuit, next\)/);
  assert.match(js, /residentActionModeLabel\(next\)/);
  assert.match(js, /return 'rehearsal'/);
  assert.doesNotMatch(js, /next\.dryRun \? 'dry-run' : null/);
  assert.doesNotMatch(js, /const text = String\(brief\?\.text/);
  assert.match(js, /groupResidentConsequences/);
  assert.match(js, /toggleResidentConsequencesPanel\(consequenceRows\)/);
  assert.match(js, /function toggleResidentConsequencesPanel\(items\)/);
  assert.doesNotMatch(js, /No recent consequences\./);
  assert.match(js, /residentHomeConsequenceRows/);
  assert.match(js, /residentHomeConsequenceRows\(state\.recentConsequences \|\| consequences \|\| \[\]\)/);
  assert.match(js, /!groupResidentSchedulerEvidence\(row\)/);
  assert.match(js, /renderResidentConsequenceGroup/);
  assert.match(js, /renderResidentConsequenceTitle/);
  assert.match(js, /renderResidentConsequenceSummary/);
  assert.match(js, /raw === 'pursuit_closed_by_receipt'/);
  assert.match(js, /return 'Pursuit closed'/);
  assert.match(js, /renderResidentConsequenceMeta/);
  assert.match(js, /groupResidentSchedulerEvidence/);
  assert.match(js, /renderResidentSchedulerEvidenceGroup/);
  assert.doesNotMatch(js, /consequenceRows\.map\(renderResidentConsequenceRow\)/);
  assert.doesNotMatch(js, /\[c\.pursuitId, c\.at \? timeSinceSafe\(c\.at\) : null\]/);
  assert.doesNotMatch(js, /<h3>\$\{escapeHtml\(p\.title/);
  assert.doesNotMatch(js, /<span>\$\{escapeHtml\(p\.status \|\| 'active'\)\}<\/span>/);
  assert.match(js, /renderResidentPursuitAuthority\(p\)/);
  assert.match(js, /if \(_pulseEls\.state\)/);
  assert.match(js, /if \(_pulseEls\.energy\)/);
  assert.doesNotMatch(js, /currentTab === 'intelligence'/);
  assert.doesNotMatch(js, /loadIntelligence/);
  assert.doesNotMatch(js, /setupIntelSynthButton/);
  assert.match(server, /resident agency state/);
  assert.match(server, /Routine organs stay hidden until they need action/);
  assert.doesNotMatch(server, /Tiles, pulse, chat/);
  assert.doesNotMatch(server, /intelligence:\s*\{\s*kind: 'dashboard'/);
  assert.doesNotMatch(server, /about:\s*\{\s*kind: 'shared'/);

  assert.match(css, /\.h23-resident-home/);
  assert.match(css, /\.h23-resident-command/);
  assert.match(css, /\.h23-resident-action-btn\.danger/);
  assert.match(css, /\.h23-resident-stream/);
  assert.doesNotMatch(css, /\.h23-resident-diagnostics/);
  assert.match(css, /\.h23-organ-drawer/);
  assert.match(css, /\.h23-organ-panel/);
  assert.match(css, /\.h23-system-rail/);
  assert.match(css, /\.h23-system-runtime/);
  assert.doesNotMatch(css, /\.h23-dashboard-identity/);
  assert.doesNotMatch(css, /\.h23-system-rail \.time-cluster/);
  assert.doesNotMatch(css, /\.h23-system-rail \.cosmo-status/);
  assert.doesNotMatch(css, /\.h23-intel/);
  assert.doesNotMatch(css, /\.h23-about/);
});
