import { timingSafeEqual } from "node:crypto";

import type { CoordinationDatabase, CoordinationTransaction } from "../db/index.js";
import type {
  AuthIdempotencyClaim, AuthIdempotencyResult, AuthRepository, AuthorizationState,
  ClientSessionRecord, DeviceRecord, PairingCreationCommit, PairingCreationResult,
  PairingFailureResult, PairingRedemptionCommit, PairingRedemptionResult,
  PairingSessionRecord, RefreshContext, RefreshRotationCommit, RefreshRotationResult,
  RefreshTokenRecord, RevokeResult,
} from "./types.js";

interface IdempotencyRow { requestDigest: string; resultKind: AuthIdempotencyResult["kind"]; resultJson: string }
interface PairingRow { id: string; deviceName: string; codeVerifier: string; state: PairingSessionRecord["state"]; failedAttempts: number; createdAt: string; expiresAt: string; redeemedAt: string | null }
interface DeviceRow { id: string; principalId: "user_owner"; platform: DeviceRecord["platform"]; name: string; appBuild: string; status: DeviceRecord["status"]; createdAt: string; lastSeenAt: string; revokedAt: string | null }
interface SessionRow { id: string; deviceId: string; principalId: "user_owner"; familyId: string; state: ClientSessionRecord["state"]; scopesJson: string; accessExpiresAt: string; refreshExpiresAt: string; createdAt: string; rotatedAt: string | null; rotatedToSessionId: string | null; revokedAt: string | null; revokeReason: ClientSessionRecord["revokeReason"] | null }
interface TokenRow { id: string; familyId: string; sessionId: string; tokenDigest: string; state: RefreshTokenRecord["state"]; createdAt: string; expiresAt: string; rotatedAt: string | null; rotatedToTokenId: string | null; revokedAt: string | null; revokeReason: RefreshTokenRecord["revokeReason"] | null }

const PAIRING = `SELECT id, requested_device_name AS deviceName, code_verifier AS codeVerifier, state, failed_attempts AS failedAttempts, created_at AS createdAt, expires_at AS expiresAt, redeemed_at AS redeemedAt FROM pairing_sessions`;
const DEVICE = `SELECT id, principal_id AS principalId, platform, name, app_build AS appBuild, status, created_at AS createdAt, last_seen_at AS lastSeenAt, revoked_at AS revokedAt FROM devices`;
const SESSION = `SELECT id, device_id AS deviceId, principal_id AS principalId, family_id AS familyId, state, scopes_json AS scopesJson, access_expires_at AS accessExpiresAt, refresh_expires_at AS refreshExpiresAt, created_at AS createdAt, rotated_at AS rotatedAt, rotated_to_session_id AS rotatedToSessionId, revoked_at AS revokedAt, revoke_reason AS revokeReason FROM client_sessions`;
const TOKEN = `SELECT token_id AS id, family_id AS familyId, session_id AS sessionId, token_digest AS tokenDigest, state, created_at AS createdAt, expires_at AS expiresAt, rotated_at AS rotatedAt, rotated_to_token_id AS rotatedToTokenId, revoked_at AS revokedAt, revoke_reason AS revokeReason FROM session_refresh_tokens`;

const pairing = (row: PairingRow): PairingSessionRecord => Object.freeze({ id:row.id,deviceName:row.deviceName,codeVerifier:row.codeVerifier,state:row.state,failedAttempts:row.failedAttempts,createdAt:row.createdAt,expiresAt:row.expiresAt,...(row.redeemedAt===null?{}:{redeemedAt:row.redeemedAt}) });
const device = (row: DeviceRow): DeviceRecord => Object.freeze({ id:row.id,principalId:row.principalId,platform:row.platform,name:row.name,appBuild:row.appBuild,status:row.status,createdAt:row.createdAt,lastSeenAt:row.lastSeenAt,...(row.revokedAt===null?{}:{revokedAt:row.revokedAt}) });
const session = (row: SessionRow): ClientSessionRecord => Object.freeze({ id:row.id,deviceId:row.deviceId,principalId:row.principalId,familyId:row.familyId,state:row.state,scopes:Object.freeze(JSON.parse(row.scopesJson) as ClientSessionRecord["scopes"]),accessExpiresAt:row.accessExpiresAt,refreshExpiresAt:row.refreshExpiresAt,createdAt:row.createdAt,...(row.rotatedAt===null?{}:{rotatedAt:row.rotatedAt}),...(row.rotatedToSessionId===null?{}:{rotatedToSessionId:row.rotatedToSessionId}),...(row.revokedAt===null?{}:{revokedAt:row.revokedAt}),...(row.revokeReason==null?{}:{revokeReason:row.revokeReason}) });
const token = (row: TokenRow): RefreshTokenRecord => Object.freeze({id:row.id,familyId:row.familyId,sessionId:row.sessionId,tokenDigest:row.tokenDigest,state:row.state,createdAt:row.createdAt,expiresAt:row.expiresAt,...(row.rotatedAt===null?{}:{rotatedAt:row.rotatedAt}),...(row.rotatedToTokenId===null?{}:{rotatedToTokenId:row.rotatedToTokenId}),...(row.revokedAt===null?{}:{revokedAt:row.revokedAt}),...(row.revokeReason==null?{}:{revokeReason:row.revokeReason})});
function safeEqual(left: string, right: string): boolean { const a = Buffer.from(left, "hex"); const b = Buffer.from(right, "hex"); return a.length === b.length && timingSafeEqual(a, b); }

function readIdempotency(db: Pick<CoordinationDatabase | CoordinationTransaction, "readOne">, claim: Pick<AuthIdempotencyClaim, "principalId" | "operation" | "idempotencyKeyDigest">): { requestDigest: string; result: AuthIdempotencyResult } | null {
  const row = db.readOne<IdempotencyRow>(`SELECT request_digest AS requestDigest, result_kind AS resultKind, result_ref_json AS resultJson FROM idempotency_records WHERE principal_id = ? AND operation = ? AND idempotency_key_digest = ?`, claim.principalId, claim.operation, claim.idempotencyKeyDigest);
  return row ? { requestDigest: row.requestDigest, result: JSON.parse(row.resultJson) as AuthIdempotencyResult } : null;
}
function storeIdempotency(tx: CoordinationTransaction, claim: AuthIdempotencyClaim, result: AuthIdempotencyResult): void {
  tx.run(`INSERT INTO idempotency_records (principal_id, operation, idempotency_key_digest, request_digest, result_kind, result_ref_json, request_id, correlation_id, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`, claim.principalId, claim.operation, claim.idempotencyKeyDigest, claim.requestDigest, result.kind, JSON.stringify(result), claim.requestId, claim.correlationId, claim.at);
}
function eventVersion(tx: CoordinationTransaction, kind: string, id: string): number { return (tx.readOne<{ count: number }>("SELECT count(*) AS count FROM events WHERE aggregate_kind = ? AND aggregate_id = ?", kind, id)?.count ?? 0) + 1; }
function authEvent(tx: CoordinationTransaction, claim: AuthIdempotencyClaim, kind: string, id: string, outcome: string) { return { type: "auth.updated", aggregateKind: kind, aggregateId: id, aggregateVersion: eventVersion(tx, kind, id), channelId: null, actorPrincipalId: "user_owner", requestId: claim.requestId, correlationId: claim.correlationId, payload: { operation: claim.operation, outcome }, createdAt: claim.at }; }
function conflictOrReplay(tx: CoordinationTransaction, claim: AuthIdempotencyClaim): AuthIdempotencyResult | "conflict" | null { const found = readIdempotency(tx, claim); return !found ? null : found.requestDigest === claim.requestDigest ? found.result : "conflict"; }
function revokeFamily(tx: CoordinationTransaction, familyId: string, at: string, reason: string): void {
  tx.run("UPDATE session_refresh_tokens SET state = 'revoked', revoked_at = ?, revoke_reason = ? WHERE family_id = ? AND state <> 'revoked'", at, reason, familyId);
  tx.run("UPDATE client_sessions SET state = 'revoked', revoked_at = ?, revoke_reason = ? WHERE family_id = ? AND state = 'active'", at, reason, familyId);
}

export class SqliteAuthRepository implements AuthRepository {
  constructor(private readonly database: CoordinationDatabase) {}
  async getIdempotency(input: Pick<AuthIdempotencyClaim, "principalId" | "operation" | "idempotencyKeyDigest">) { return readIdempotency(this.database, input); }
  async getPairing(id: string) { const row = this.database.readOne<PairingRow>(`${PAIRING} WHERE id = ?`, id); return row ? pairing(row) : null; }
  async createPairing(input: PairingCreationCommit): Promise<PairingCreationResult> {
    return this.database.mutateWithEvent<PairingCreationResult>((tx) => {
      const replay = conflictOrReplay(tx, input.idempotency); if (replay === "conflict") return { value: { outcome: "conflict" as const }, event: authEvent(tx, input.idempotency, "pairingSession", input.pairing.id, "conflict") }; if (replay) return { value: { outcome: "replayed" as const, pairing: (replay as Extract<AuthIdempotencyResult,{kind:"pairing"}>).pairing }, event: authEvent(tx, input.idempotency, "pairingSession", input.pairing.id, "replayed") };
      tx.run("INSERT OR IGNORE INTO principals (id, kind, created_at) VALUES ('user_owner', 'owner', ?)", input.idempotency.at);
      tx.run("INSERT INTO pairing_sessions (id, requested_device_name, code_verifier, state, failed_attempts, created_at, expires_at, redeemed_at) VALUES (?, ?, ?, ?, ?, ?, ?, NULL)", input.pairing.id, input.pairing.deviceName, input.pairing.codeVerifier, input.pairing.state, input.pairing.failedAttempts, input.pairing.createdAt, input.pairing.expiresAt);
      const result: AuthIdempotencyResult = { kind: "pairing", pairing: { id: input.pairing.id, state: input.pairing.state, expiresAt: input.pairing.expiresAt } }; storeIdempotency(tx, input.idempotency, result);
      return { value: { outcome: "created" as const, pairing: result.pairing }, event: authEvent(tx, input.idempotency, "pairingSession", input.pairing.id, "created") };
    }).value;
  }
  async recordPairingFailure(input: { pairingSessionId: string; at: string; maximumFailures: number; idempotency: AuthIdempotencyClaim }): Promise<PairingFailureResult> {
    return this.database.mutateWithEvent<PairingFailureResult>((tx) => {
      const replay = conflictOrReplay(tx, input.idempotency); if (replay === "conflict") return { value: { outcome: "conflict" as const }, event: authEvent(tx,input.idempotency,"pairingSession",input.pairingSessionId,"conflict") }; if (replay) return { value: (replay as Extract<AuthIdempotencyResult,{kind:"pairing_failure"}>).result, event: authEvent(tx,input.idempotency,"pairingSession",input.pairingSessionId,"replayed") };
      const row = tx.readOne<PairingRow>(`${PAIRING} WHERE id = ?`, input.pairingSessionId); let result: PairingFailureResult;
      if (!row) result = { outcome: "not_found" }; else if (row.state !== "pending") result = { outcome: "terminal", state: row.state }; else if (row.expiresAt <= input.at) { tx.run("UPDATE pairing_sessions SET state = 'expired' WHERE id = ?", row.id); result = { outcome: "expired" }; } else { const failures = row.failedAttempts + 1; const locked = failures >= input.maximumFailures; tx.run("UPDATE pairing_sessions SET failed_attempts = ?, state = ? WHERE id = ?", failures, locked ? "locked" : "pending", row.id); result = locked ? { outcome: "locked" } : { outcome: "pending", failedAttempts: failures }; }
      storeIdempotency(tx,input.idempotency,{kind:"pairing_failure",result}); return { value: result, event: authEvent(tx,input.idempotency,"pairingSession",input.pairingSessionId,result.outcome) };
    }).value;
  }
  async redeemPairing(input: PairingRedemptionCommit): Promise<PairingRedemptionResult> {
    return this.database.mutateWithEvent<PairingRedemptionResult>((tx) => {
      const replay = conflictOrReplay(tx,input.idempotency); if (replay === "conflict") return {value:{outcome:"conflict" as const},event:authEvent(tx,input.idempotency,"pairingSession",input.pairingSessionId,"conflict")}; if (replay) { if(replay.kind==="pairing_failure"&&replay.result.outcome==="expired") return {value:{outcome:"expired" as const},event:authEvent(tx,input.idempotency,"pairingSession",input.pairingSessionId,"replayed")}; const r=replay as Extract<AuthIdempotencyResult,{kind:"redemption"}>; return {value:{outcome:"replayed" as const,pairing:r.pairing,device:r.device,session:r.session},event:authEvent(tx,input.idempotency,"pairingSession",input.pairingSessionId,"replayed")}; }
      const row=tx.readOne<PairingRow>(`${PAIRING} WHERE id = ?`,input.pairingSessionId); if(!row) return {value:{outcome:"not_found" as const},event:authEvent(tx,input.idempotency,"pairingSession",input.pairingSessionId,"not_found")}; if(row.state!=="pending") return {value:{outcome:"terminal" as const,state:row.state},event:authEvent(tx,input.idempotency,"pairingSession",row.id,"terminal")}; if(row.expiresAt<=input.redeemedAt){tx.run("UPDATE pairing_sessions SET state='expired' WHERE id=?",row.id); const result={outcome:"expired" as const}; storeIdempotency(tx,input.idempotency,{kind:"pairing_failure",result}); return {value:result,event:authEvent(tx,input.idempotency,"pairingSession",row.id,"expired")};}
      tx.run("UPDATE pairing_sessions SET state='redeemed', redeemed_at=? WHERE id=?",input.redeemedAt,row.id); const d=input.device,s=input.session,t=input.refreshToken;
      tx.run("INSERT INTO devices (id,principal_id,platform,name,app_build,status,created_at,last_seen_at,revoked_at) VALUES (?,?,?,?,?,?,?,?,NULL)",d.id,d.principalId,d.platform,d.name,d.appBuild,d.status,d.createdAt,d.lastSeenAt);
      tx.run("INSERT INTO client_sessions (id,device_id,principal_id,family_id,state,scopes_json,access_expires_at,refresh_expires_at,created_at) VALUES (?,?,?,?,?,?,?,?,?)",s.id,s.deviceId,s.principalId,s.familyId,s.state,JSON.stringify(s.scopes),s.accessExpiresAt,s.refreshExpiresAt,s.createdAt);
      tx.run("INSERT INTO session_refresh_tokens (token_id,family_id,session_id,token_digest,state,created_at,expires_at) VALUES (?,?,?,?,?,?,?)",t.id,t.familyId,t.sessionId,t.tokenDigest,t.state,t.createdAt,t.expiresAt);
      const redeemed={id:row.id,state:"redeemed" as const,expiresAt:row.expiresAt,redeemedAt:input.redeemedAt}; const stored:AuthIdempotencyResult={kind:"redemption",pairing:redeemed,device:d,session:s}; storeIdempotency(tx,input.idempotency,stored); return {value:{outcome:"redeemed" as const,pairing:redeemed,device:d,session:s},event:authEvent(tx,input.idempotency,"pairingSession",row.id,"redeemed")};
    }).value;
  }
  async getRefreshContext(id:string):Promise<RefreshContext|null>{const t=this.database.readOne<TokenRow>(`${TOKEN} WHERE token_id = ?`,id);if(!t)return null;const s=this.database.readOne<SessionRow>(`${SESSION} WHERE id = ?`,t.sessionId);if(!s)return null;const d=this.database.readOne<DeviceRow>(`${DEVICE} WHERE id = ?`,s.deviceId);return d?{token:token(t),session:session(s),device:device(d)}:null;}
  async getAuthorizationState(id:string):Promise<AuthorizationState|null>{const s=this.database.readOne<SessionRow>(`${SESSION} WHERE id = ?`,id);if(!s)return null;const d=this.database.readOne<DeviceRow>(`${DEVICE} WHERE id = ?`,s.deviceId);if(!d)return null;const familyRevoked=(this.database.readOne<{count:number}>("SELECT count(*) AS count FROM session_refresh_tokens WHERE family_id=? AND state='revoked'",s.familyId)?.count??0)>0;return{session:session(s),device:device(d),familyRevoked};}
  async rotateRefresh(input:RefreshRotationCommit):Promise<RefreshRotationResult>{return this.database.mutateWithEvent(tx=>{const replay=conflictOrReplay(tx,input.idempotency);const evt=(out:string)=>authEvent(tx,input.idempotency,"clientSession",input.successorSession.id,out);if(replay==="conflict")return{value:{outcome:"conflict" as const},event:evt("conflict")};if(replay){if(replay.kind==="refresh_failure")return{value:replay.result,event:evt("replayed")};const r=replay as Extract<AuthIdempotencyResult,{kind:"refresh"}>;return{value:{outcome:"replayed" as const,session:r.session,device:r.device},event:evt("replayed")};}const tr=tx.readOne<TokenRow>(`${TOKEN} WHERE token_id=?`,input.currentTokenId);if(!tr||!safeEqual(tr.tokenDigest,input.presentedTokenDigest))return{value:{outcome:"invalid" as const},event:evt("invalid")};let failure:RefreshRotationResult|null=null;if(tr.state==="rotated"){revokeFamily(tx,tr.familyId,input.rotatedAt,"refresh_replay");failure={outcome:"replay",familyId:tr.familyId};}else if(tr.state==="revoked")failure={outcome:"revoked"};else if(tr.state==="expired"||tr.expiresAt<=input.rotatedAt){tx.run("UPDATE session_refresh_tokens SET state='expired' WHERE token_id=?",tr.id);failure={outcome:"expired"};}const sr=tx.readOne<SessionRow>(`${SESSION} WHERE id=?`,tr.sessionId);const dr=sr?tx.readOne<DeviceRow>(`${DEVICE} WHERE id=?`,sr.deviceId):undefined;if(!failure&&(!sr||sr.state!=="active"))failure={outcome:"session_inactive"};if(!failure&&(!dr||dr.status!=="active"))failure={outcome:"device_inactive"};if(failure){storeIdempotency(tx,input.idempotency,{kind:"refresh_failure",result:failure});return{value:failure,event:evt(failure.outcome)}}const s=input.successorSession,t=input.successorToken;tx.run("INSERT INTO client_sessions (id,device_id,principal_id,family_id,state,scopes_json,access_expires_at,refresh_expires_at,created_at) VALUES (?,?,?,?,?,?,?,?,?)",s.id,s.deviceId,s.principalId,s.familyId,s.state,JSON.stringify(s.scopes),s.accessExpiresAt,s.refreshExpiresAt,s.createdAt);tx.run("INSERT INTO session_refresh_tokens (token_id,family_id,session_id,token_digest,state,created_at,expires_at) VALUES (?,?,?,?,?,?,?)",t.id,t.familyId,t.sessionId,t.tokenDigest,t.state,t.createdAt,t.expiresAt);tx.run("UPDATE session_refresh_tokens SET state='rotated',rotated_at=?,rotated_to_token_id=? WHERE token_id=?",input.rotatedAt,t.id,tr.id);tx.run("UPDATE client_sessions SET state='rotated',rotated_at=?,rotated_to_session_id=? WHERE id=?",input.rotatedAt,s.id,sr!.id);const stored:AuthIdempotencyResult={kind:"refresh",device:device(dr!),session:s};storeIdempotency(tx,input.idempotency,stored);return{value:{outcome:"rotated" as const,device:stored.device,session:s},event:evt("rotated")}}).value;}
  async revokeSession(input:{sessionId:string;revokedAt:string;reason:"session_revoke";idempotency:AuthIdempotencyClaim}):Promise<RevokeResult>{return this.revoke("session",input.sessionId,input.revokedAt,input.reason,input.idempotency);}
  async revokeDevice(input:{deviceId:string;revokedAt:string;reason:"device_revoke";idempotency:AuthIdempotencyClaim}):Promise<RevokeResult>{return this.revoke("device",input.deviceId,input.revokedAt,input.reason,input.idempotency);}
  private revoke(kind:"session"|"device",id:string,at:string,reason:"session_revoke"|"device_revoke",claim:AuthIdempotencyClaim):RevokeResult{return this.database.mutateWithEvent(tx=>{const replay=conflictOrReplay(tx,claim);const evt=(out:string)=>authEvent(tx,claim,kind==="session"?"clientSession":"device",id,out);if(replay==="conflict")return{value:{outcome:"conflict" as const},event:evt("conflict")};if(replay)return{value:{outcome:"replayed" as const},event:evt("replayed")};const row=kind==="session"?tx.readOne<SessionRow>(`${SESSION} WHERE id=?`,id):tx.readOne<DeviceRow>(`${DEVICE} WHERE id=?`,id);let result:RevokeResult;if(!row)result={outcome:"not_found"};else if((kind==="session"?(row as SessionRow).state:(row as DeviceRow).status)!=="active")result={outcome:"already_inactive"};else{if(kind==="session")revokeFamily(tx,(row as SessionRow).familyId,at,reason);else{tx.run("UPDATE devices SET status='revoked',revoked_at=? WHERE id=?",at,id);for(const s of tx.readAll<{familyId:string}>("SELECT DISTINCT family_id AS familyId FROM client_sessions WHERE device_id=?",id))revokeFamily(tx,s.familyId,at,reason);}result={outcome:"revoked"};}storeIdempotency(tx,claim,{kind:"revoke",result});return{value:result,event:evt(result.outcome)}}).value;}
}
