import { createPublicKey, verify } from "node:crypto";
import { openCoordinationDatabase } from "../db/index.js";
import { authorityReceiptSigningPayload, validateAuthorityEpochTransition, type AuthorityEpoch, type AuthorityRolloutReceipt } from "../epochs/index.js";
import { FEATURE_FLAG_REGISTRY } from "../schema/contract-registry.js";
import { assertCoordinationId } from "../ids/index.js";

export interface M14AuthorityInput { databasePath:string;receipt:AuthorityRolloutReceipt;publicKeyPem:string;activeCanonicalWriters:readonly string[];requestId:string;correlationId:string;apply?:boolean;liveAuthorized?:boolean }
export function executeM14AuthorityTransition(input:M14AuthorityInput){
  const database=openCoordinationDatabase({path:input.databasePath,applicationVersion:"home23-coordination-m14-authority"});
  try{const history=database.readAll<{capability:AuthorityEpoch["capability"];epoch:number;mode:AuthorityEpoch["mode"];writer:string;effectiveAtEventSequence:number|null;rollbackEpoch:number|null}>(`SELECT capability,epoch,mode,writer,effective_at_event_sequence AS effectiveAtEventSequence,rollback_epoch AS rollbackEpoch FROM authority_epochs WHERE capability='messages' ORDER BY epoch`);if(history.length===0)throw new Error("messages authority history is missing");const current=history.at(-1)!;const proposed:AuthorityEpoch={capability:"messages",epoch:input.receipt.toEpoch,mode:input.receipt.toAuthority.mode,writer:input.receipt.toAuthority.writer,effectiveAtEventSequence:input.receipt.effectiveAtEventSequence,rollbackEpoch:input.receipt.rollbackTarget};
    const expectedFlags=Object.keys(FEATURE_FLAG_REGISTRY);const enabledFlags=expectedFlags.filter(key=>input.receipt.activeFlags[key]===true);if(expectedFlags.some(key=>typeof input.receipt.activeFlags[key]!=="boolean"))throw new Error("authority receipt must contain every registered Boolean flag");const required=input.receipt.toAuthority.mode==="canonical"?["coordination.process.enabled","coordination.public_api.enabled","coordination.resident.jerry.enabled"]:[];if(enabledFlags.length!==required.length||required.some(flag=>!enabledFlags.includes(flag)))throw new Error(input.receipt.toAuthority.mode==="canonical"?"M14 authority receipt must enable exactly process, public API, and Jerry":"shadow/rollback authority receipt must remain feature-off");
    assertCoordinationId("request",input.requestId);assertCoordinationId("correlation",input.correlationId);const validation=validateAuthorityEpochTransition({current,proposed,history,receipt:input.receipt,activeCanonicalWriters:input.activeCanonicalWriters,verifySignature:(payload,signature)=>signature.algorithm==="ed25519"&&verify(null,Buffer.from(payload),createPublicKey(input.publicKeyPem),Buffer.from(signature.value,"base64"))});if(validation.decision!=="valid")throw new Error(`M14 authority transition denied: ${validation.reason}`);
    const plan={mode:input.apply===true?"apply":"preflight",current,proposed,receiptDigest:validation.receiptDigest??null,mutated:false};if(input.apply!==true)return plan;if(input.liveAuthorized!==true)throw new Error("M14 authority apply requires --live-authorized and a valid signed receipt");
    database.mutateWithEvent(tx=>{tx.run("INSERT INTO authority_epochs (capability,epoch,mode,writer,effective_at_event_sequence,rollback_epoch,receipt_json,created_at) VALUES (?,?,?,?,?,?,?,?)",proposed.capability,proposed.epoch,proposed.mode,proposed.writer,proposed.effectiveAtEventSequence,proposed.rollbackEpoch,JSON.stringify(input.receipt),input.receipt.issuedAt);return{value:null,event:{type:"authority.epoch_changed",aggregateKind:"authorityEpoch",aggregateId:"authority:messages",aggregateVersion:proposed.epoch,channelId:null,actorPrincipalId:input.receipt.operator,requestId:input.requestId,correlationId:input.correlationId,payload:{capability:"messages",epoch:proposed.epoch,writer:proposed.writer,mode:proposed.mode},createdAt:input.receipt.issuedAt}};});return{...plan,mutated:true};
  }finally{database.close();}
}
