import assert from "node:assert/strict";import {mkdirSync,mkdtempSync,rmSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import test,{type TestContext} from "node:test";
import {AUTH_TOKEN_LIFETIMES,createAuthService,SqliteAuthRepository,type AuthAuditRecord} from "../../../src/coordination/auth/index.js";import {openCoordinationDatabase} from "../../../src/coordination/db/index.js";import {generateCoordinationId} from "../../../src/coordination/ids/index.js";

const mutation=(key:string)=>({idempotencyKey:key,requestId:generateCoordinationId("request"),correlationId:generateCoordinationId("correlation")});
// One paired iPad on a fresh SQLite home whose clock the test moves; the first rotation lands at 12:01:00.
async function pairedHome(t:TestContext,clock:{now:Date}){const root=mkdtempSync(join(tmpdir(),"home23-auth-sqlite-"));mkdirSync(root,{recursive:true});t.after(()=>rmSync(root,{recursive:true,force:true}));const db=openCoordinationDatabase({path:join(root,"coord.sqlite3")});t.after(()=>db.close());const audit:AuthAuditRecord[]=[];const service=createAuthService({repository:new SqliteAuthRepository(db),keyMaterial:Buffer.alloc(32,7),now:()=>clock.now,audit:{record:(entry)=>audit.push(entry)},admissionVerifier:{verifyLocalOperator:()=>({allowed:true,network:"loopback",rateLimitKey:"operator"}),verifyClient:()=>({allowed:true,network:"loopback",rateLimitKey:"client"})}});const issued=await service.issuePairing({deviceName:"Owner iPad",operator:"loopback",mutation:mutation("sqlite-pairing-issue-0001")});const paired=await service.redeemPairing({pairingSessionId:issued.pairingSession.id,pairingCode:issued.pairingCode,network:"loopback",device:{platform:"ios",name:"Owner iPad",appBuild:"181"},mutation:mutation("sqlite-pairing-redeem-0001")});clock.now=new Date("2026-08-25T12:01:00.000Z");const first=await service.refreshSession({refreshToken:paired.refreshToken,network:"loopback",mutation:mutation("sqlite-refresh-first-0001")});const refresh=(refreshToken:string,key:string)=>service.refreshSession({refreshToken,network:"loopback",mutation:mutation(key)});const revokeReason=(sessionId:string)=>db.readOne<{reason:string|null}>("SELECT revoke_reason AS reason FROM client_sessions WHERE id=?",sessionId)?.reason;return{db,service,audit,paired,first,refresh,revokeReason};}

test("SQLite reuse of a retired refresh token inside the grace window re-delivers the identical successor credentials and keeps the family live",async t=>{const clock={now:new Date("2026-08-25T12:00:00.000Z")};const h=await pairedHome(t,clock);clock.now=new Date("2026-08-25T12:01:01.000Z");
  const again=await h.refresh(h.paired.refreshToken,"sqlite-refresh-retry-0001");assert.equal(again.accessToken,h.first.accessToken);assert.equal(again.refreshToken,h.first.refreshToken);assert.equal(again.clientSession.id,h.first.clientSession.id);assert.deepEqual(again,h.first);assert.equal(h.audit.at(-1)?.reason,"refresh_reissued");
  assert.equal(h.db.readOne<{count:number}>("SELECT count(*) AS count FROM session_refresh_tokens WHERE state='revoked'")?.count,0);assert.equal(h.db.readOne<{count:number}>("SELECT count(*) AS count FROM client_sessions")?.count,2);
  assert.equal(h.db.readOne<{count:number}>("SELECT count(*) AS count FROM events WHERE aggregate_kind='clientSession' AND aggregate_id=? AND json_extract(payload_json,'$.outcome')='reissued'",h.first.clientSession.id)?.count,1);
  clock.now=new Date("2026-08-25T12:02:00.000Z");const next=await h.refresh(h.first.refreshToken,"sqlite-refresh-next-0001");assert.notEqual(next.clientSession.id,h.first.clientSession.id);assert.equal(h.audit.at(-1)?.reason,"refresh_rotated");assert.equal((await h.service.validateAccessToken({accessToken:next.accessToken,network:"loopback",requiredScopes:["product:read"]})).sessionId,next.clientSession.id);});

test("SQLite reuse of a retired refresh token after its successor rotated revokes the family",async t=>{const clock={now:new Date("2026-08-25T12:00:00.000Z")};const h=await pairedHome(t,clock);clock.now=new Date("2026-08-25T12:01:30.000Z");const live=await h.refresh(h.first.refreshToken,"sqlite-refresh-second-0001");clock.now=new Date("2026-08-25T12:01:31.000Z");
  await assert.rejects(h.refresh(h.paired.refreshToken,"sqlite-refresh-replay-0001"),{name:"AuthError",reasonCode:"refresh_replay_family_revoked",httpStatus:409});assert.equal(h.revokeReason(live.clientSession.id),"refresh_replay");await assert.rejects(h.service.validateAccessToken({accessToken:live.accessToken,network:"loopback",requiredScopes:["product:read"]}),{reasonCode:"session_revoked"});});

test("SQLite reuse of a retired refresh token after the grace window revokes the family",async t=>{const clock={now:new Date("2026-08-25T12:00:00.000Z")};const h=await pairedHome(t,clock);clock.now=new Date(clock.now.getTime()+AUTH_TOKEN_LIFETIMES.refreshReuseGraceMs+1000);
  await assert.rejects(h.refresh(h.paired.refreshToken,"sqlite-refresh-late-0001"),{name:"AuthError",reasonCode:"refresh_replay_family_revoked",httpStatus:409});assert.equal(h.revokeReason(h.first.clientSession.id),"refresh_replay");assert.equal(h.audit.at(-1)?.reason,"refresh_replay_family_revoked");});

test("SQLite reuse of a token whose rotation stored no context (a pre-187 record) still revokes the family",async t=>{const clock={now:new Date("2026-08-25T12:00:00.000Z")};const h=await pairedHome(t,clock);
  // Build 186 stored the rotation without its credential context; nothing can be re-derived from it.
  h.db.mutateWithEvent(tx=>{tx.run("UPDATE idempotency_records SET result_ref_json=json_remove(result_ref_json,'$.credentialContext') WHERE result_kind='refresh'");return{value:undefined,event:{type:"test.pre187_record",aggregateKind:"home",aggregateId:generateCoordinationId("home"),aggregateVersion:1,channelId:null,actorPrincipalId:"user_owner",requestId:generateCoordinationId("request"),correlationId:generateCoordinationId("correlation"),payload:{},createdAt:clock.now.toISOString()}};});
  clock.now=new Date("2026-08-25T12:01:01.000Z");await assert.rejects(h.refresh(h.paired.refreshToken,"sqlite-refresh-retry-0001"),{name:"AuthError",reasonCode:"refresh_replay_family_revoked",httpStatus:409});assert.equal(h.revokeReason(h.first.clientSession.id),"refresh_replay");});

test("SQLite auth pairing is durable, idempotent, and validates a stored active session",async t=>{const root=mkdtempSync(join(tmpdir(),"home23-auth-sqlite-"));mkdirSync(root,{recursive:true});t.after(()=>rmSync(root,{recursive:true,force:true}));const db=openCoordinationDatabase({path:join(root,"coord.sqlite3")});t.after(()=>db.close());const now=()=>new Date("2026-08-25T12:00:00.000Z");const service=createAuthService({repository:new SqliteAuthRepository(db),keyMaterial:Buffer.alloc(32,7),now,admissionVerifier:{verifyLocalOperator:()=>({allowed:true,network:"loopback",rateLimitKey:"operator"}),verifyClient:()=>({allowed:true,network:"loopback",rateLimitKey:"client"})}});const mutation=(key:string)=>({idempotencyKey:key,requestId:generateCoordinationId("request"),correlationId:generateCoordinationId("correlation")});const issued=await service.issuePairing({deviceName:"M14 fixture",operator:"loopback",mutation:mutation("sqlite-pairing-issue-0001")});const replay=await service.issuePairing({deviceName:"M14 fixture",operator:"loopback",mutation:mutation("sqlite-pairing-issue-0001")});assert.equal(replay.pairingSession.id,issued.pairingSession.id);assert.equal(replay.pairingCode,issued.pairingCode);const paired=await service.redeemPairing({pairingSessionId:issued.pairingSession.id,pairingCode:issued.pairingCode,network:"loopback",device:{platform:"macos",name:"M14 fixture",appBuild:"test"},mutation:mutation("sqlite-pairing-redeem-0001")});assert.equal((await service.validateAccessToken({accessToken:paired.accessToken,network:"loopback",requiredScopes:["message:send"]})).sessionId,paired.clientSession.id);assert.equal(db.readOne<{count:number}>("SELECT count(*) AS count FROM client_sessions")?.count,1);});
