export const RESIDENT_PROTOCOL_VERSION = 1 as const;
export const SUPPORTED_RESIDENT_PROTOCOL_VERSIONS = [RESIDENT_PROTOCOL_VERSION] as const;

export const MAX_CAPABILITY_LIFETIME_MS = 120_000;
export const DEFAULT_CLOCK_SKEW_MS = 5_000;
export const DEFAULT_MAX_FRAME_BYTES = 256 * 1024;
